#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const root = __dirname;
const ignoredDirectories = new Set(['.git', 'node_modules']);

function findMarkdownFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    if (entry.name.startsWith('.') || ignoredDirectories.has(entry.name)) return [];
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return findMarkdownFiles(fullPath);
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.md')) return [];
    const relativePath = path.relative(root, fullPath).split(path.sep).join('/');
    return relativePath === 'README.md' ? [] : [relativePath];
  });
}

const files = findMarkdownFiles(root).sort((a, b) => a.localeCompare(b));
const documents = files.map(filePath => ({
  path: filePath,
  content: fs.readFileSync(path.join(root, filePath), 'utf8')
}));
const output = `// Generated by generate-library.js. Do not edit manually.\nwindow.MARKDOWN_FILES = ${JSON.stringify(documents, null, 2)};\n`;
fs.writeFileSync(path.join(root, 'library-files.js'), output);

// Give the generated library a new URL so GitHub Pages and browsers do not
// continue serving a previously cached article list.
const indexPath = path.join(root, 'index.html');
if (fs.existsSync(indexPath)) {
  const indexHtml = fs.readFileSync(indexPath, 'utf8');
  const cacheVersion = Date.now();
  const refreshedHtml = indexHtml.replace(
    /library-files\.js(?:\?v=\d+)?/,
    `library-files.js?v=${cacheVersion}`
  );
  fs.writeFileSync(indexPath, refreshedHtml);
}

console.log(`Updated library-files.js with ${files.length} Markdown article${files.length === 1 ? '' : 's'}.`);
