const files=window.MARKDOWN_FILES||[],grid=document.querySelector('#articleGrid'),filters=document.querySelector('#filters'),search=document.querySelector('#searchInput'),dialog=document.querySelector('#readerDialog'),content=document.querySelector('#articleContent'),toc=document.querySelector('#tableOfContents'),toast=document.querySelector('#toast');let activeCategory='All',articles=[];
if(window.marked)marked.setOptions({gfm:true,breaks:false});
const encodePath=path=>path.split('/').map(encodeURIComponent).join('/');
const cleanTitle=path=>decodeURIComponent(path.split('/').pop()).replace(/\.md$/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const categoryOf=path=>path.includes('/')?path.split('/')[0]:'General';
const strip=text=>text.replace(/^---[\s\S]*?---\s*/,'').replace(/```[\s\S]*?```/g,' ').replace(/[#>*_`\[\]()-]/g,' ').replace(/\s+/g,' ').trim();
const heading=text=>{const match=text.replace(/^---[\s\S]*?---\s*/,'').match(/^#\s+(.+)$/m);return match?match[1].replace(/[*_`]/g,'').trim():''};
const excerpt=text=>{const body=strip(text).replace(/^.+?(?=\s[A-Z])/, '').trim();return body.slice(0,190)+(body.length>190?'…':'')};
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
async function loadLibrary(){articles=await Promise.all(files.map(async item=>{const path=typeof item==='string'?item:item.path;let text=typeof item==='object'&&item.content?item.content:'';if(!text&&location.protocol!=='file:')try{const response=await fetch(encodePath(path));if(response.ok)text=await response.text()}catch{}const words=text.trim()?text.trim().split(/\s+/).length:0;return{path,text,title:heading(text)||cleanTitle(path),category:categoryOf(path),description:text?excerpt(text):'This article could not be loaded. Run node generate-library.js to refresh the library.',minutes:Math.max(1,Math.ceil(words/220)),words}}));renderFilters();render();updateStats();const requested=new URLSearchParams(location.search).get('article');if(requested&&articles.some(a=>a.path===requested))openArticle(articles.find(a=>a.path===requested))}
function updateStats(){document.querySelector('#articleCount').textContent=articles.length;document.querySelector('#categoryCount').textContent=new Set(articles.map(a=>a.category)).size;document.querySelector('#readingMinutes').textContent=articles.reduce((sum,a)=>sum+a.minutes,0)}
function renderFilters(){const cats=['All',...new Set(articles.map(a=>a.category).sort())];filters.innerHTML=cats.map(cat=>`<button class="filter ${cat==='All'?'active':''}" data-category="${cat}">${cat} <span>${cat==='All'?articles.length:articles.filter(a=>a.category===cat).length}</span></button>`).join('');filters.querySelectorAll('button').forEach(button=>button.onclick=()=>{activeCategory=button.dataset.category;filters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));render()})}
function render(){const query=search.value.trim().toLowerCase(),shown=articles.filter(a=>(activeCategory==='All'||a.category===activeCategory)&&(!query||`${a.title} ${a.category} ${a.text}`.toLowerCase().includes(query)));grid.innerHTML='';shown.forEach(article=>{const card=document.createElement('article');card.className='article-card';card.tabIndex=0;card.innerHTML=`<div class="card-top"><span class="category">${article.category}</span><span class="read-time">${article.minutes} min read</span></div><h3>${article.title}</h3><p>${article.description}</p><div class="card-bottom"><span>${article.words.toLocaleString()} words</span><span>→</span></div>`;card.onclick=()=>openArticle(article);card.onkeydown=e=>{if(e.key==='Enter')openArticle(article)};grid.append(card)});document.querySelector('#emptyState').hidden=shown.length>0}
function slug(value){return value.toLowerCase().replace(/<[^>]+>/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function openArticle(article){if(!article)return;document.querySelector('#readerPath').textContent=article.path;document.querySelector('#rawLink').href=encodePath(article.path);content.innerHTML=window.marked?marked.parse(article.text):`<pre>${article.text}</pre>`;const headings=[...content.querySelectorAll('h2,h3')];toc.innerHTML='';headings.forEach((h,i)=>{h.id=`${slug(h.textContent)}-${i}`;const a=document.createElement('a');a.href=`#${h.id}`;a.textContent=h.textContent;a.className=`level-${h.tagName.slice(1)}`;a.onclick=()=>setTimeout(()=>h.scrollIntoView({behavior:'smooth'}),50);toc.append(a)});history.replaceState({},'',`?article=${encodeURIComponent(article.path)}`);dialog.showModal();content.scrollTop=0;document.title=`${article.title} — Dev Notes`}
function closeReader(){dialog.close();history.replaceState({},'',location.pathname);document.title='Dev Notes — Technical Knowledge Library'}
document.querySelector('#closeReader').onclick=closeReader;document.querySelector('#closeReaderTop').onclick=closeReader;document.querySelector('#copyLink').onclick=async()=>{await navigator.clipboard.writeText(location.href);notify('Article link copied')};search.oninput=render;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!dialog.open)search.focus()}if(e.key==='Escape'&&dialog.open)closeReader()});dialog.addEventListener('cancel',e=>{e.preventDefault();closeReader()});loadLibrary();
